# Dependencies
highlighter:      rouge

plugins:
  - jekyll-sitemap

# Permalinks
permalink:        pretty
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

# Setup
title:            Rusith
tagline:          'Personal Blog'
description:      'A blog from a tech and art enthusiast from Sri Lanka who tries to share his thoughts and learnings'
url:              https://rusith.me
baseurl:          /

author:
  name:           'Shanaka Rusith'
paginate:         5

github:  https://github.com/rusith
linkedin:	https://www.linkedin.com/in/shanaka-rusith-12869710a
fb: https://www.facebook.com/shanaka.rusith
twitter: https://twitter.com/shanaka_rusith
goodreads: http://goodreads.com/rusith
gitlab: https://gitlab.com/rusith
imdb: https://www.imdb.com/user/ur81064939